### ISSUE TITLE
How can I avoid arrow conflitt

### ISSUE THREAD

**Issue by CamboimGabriel** [pierpo/react-archer#132]
![image](https://user-images.githubusercontent.com/36650520/108445014-71550900-723a-11eb-9ccc-cdfee3b3ed44.png)
![image](https://user-images.githubusercontent.com/36650520/108445062-8336ac00-723a-11eb-874d-9b5e2b31fe6b.png)

Here is the two types of arrows. In one case (curved), none arrows are in conflict, but when I turn the "no curves" mode on, one conflict is generated, what can I do to prevent this?

**Comment by pierpo** [comment]
Hi @CamboimGabriel ! Great usage of the lib, love it :wink: 

When you say "conflicts", you mean the arrows crossing paths? And in your case in a very misleading way? (because there is a confusion between two arrows)

Unfortunately there's no clean solution to that right now (besides moving your elements a little bit). Could you suggest something that would solve your issue? What would you expect in the lib's API to draw your arrows differently?

**Comment by CamboimGabriel** [comment]
Thanks, @pierpo ! I'm using it to render a BPMN workflow (but I'm starting, all layout will be prettier). About solutions, Can you put margin into your arrows?

**Comment by pierpo** [comment]
Well there is an `offset` setting but I think it's only available on the `ArcherContainer` element. I don't think it was implemented for individual elements, but that shouldn't be too difficult. Would it solve your issue?
If it solves your issue and you're interested you could try to implement it in the lib, it's a nice and easy addition 😉
