### ISSUE TITLE
curved path between short distances

### ISSUE THREAD

**Issue by farzd** [pierpo/react-archer#193]
<img width="408" alt="image" src="https://github.com/pierpo/react-archer/assets/1423413/3db9b7be-50eb-4ce6-ae9b-2becf0271920">

is it possible for me to make this curved? i've set source/target to be left and right. But when i change it to curved, i get this:
My ArcherElement is the fullbox and the line seems to draw from the start of the box

<img width="414" alt="image" src="https://github.com/pierpo/react-archer/assets/1423413/e6f1dd85-1d07-40c2-8be1-b947a4822d0b">

**Comment by pierpo** [comment]
Hey! This looks like a bug :thinking: 
It would be amazing if you could provide a little CodeSandbox example that reproduces the issue :blush:

**Comment by farzd** [comment]
Wow, thanks for the quick reply,
heres a simple example: https://codesandbox.io/s/modern-sound-lz2jly

**Comment by pierpo** [comment]
Thank you for the sandbox! :)

Argh, it looks like we can't achieve that with the lib as it is right now. You need more customization on the line shapes and unfortunately it's not something we can do right now. I'd love to add more customization but it's not trivial :cry: 

However, it's totally achievable if you fork the lib. You can change the drawing logic so that it looks like what you want.

You can have a look here: https://github.com/pierpo/react-archer/blob/154a1e289c6afb45a299d5be733be81e883dece2/src/SvgArrow/SvgArrow.tsx#L132
It looks convoluted, I don't even remember writing all this :joy: but if you know about SVG paths then I'm sure you can edit this to match your needs.

**Comment by farzd** [comment]
Wow. Thank you so much. 🙏🏽
