### ISSUE TITLE
Component render arrows first but not update then

### ISSUE THREAD

**Issue by InstantProgramming** [pierpo/react-archer#42]
Hello,
First, thanks for the package it fit great with the import CSV system I'm trying to code (in the part where the users have to "link" them web table columns with the CSV's).
Here is how i used the package: 
        -From the parent View, I'm mapping companyFields from states and columnsRelation from props: 
![issueParentView](https://user-images.githubusercontent.com/188211/55645229-51e49c80-57d8-11e9-925a-2d46bb836261.PNG)

          -From the LinkableAttribute component :
![issueChildView](https://user-images.githubusercontent.com/188211/55645238-59a44100-57d8-11e9-873b-60cd853f740e.PNG)

The issue : 
Arrows are created nicely, but when i try to update the columnsRelations, components are both seems like updating in console but the arrows doesn't "re-render", i tried to forceUpdate when i call my Redux Action to dispatch changes, i tried to set shouldComponentUpdate etc. 

Here is a GIF of the issue, i first create arrows, then try to update ... the updates are shown only on manual page refresh.

Thanks in advance

![issueGIF](https://user-images.githubusercontent.com/188211/55644781-2e6d2200-57d7-11e9-96a9-1d209c8084bd.gif)

**Comment by pierpo** [comment]
Hi!
Glad to hear that you like the library :blush: 

Can you show me the values of the `relations` props that you give before the improper update and after the improper update?

I want to see the changing values because there is custom logic in the library for that.

Since it's quite hard for me to debug only with questions, I'd recommend to clone the `react-archer` repo in your project and use the unminified bundle and add a debugger there. The updating part is not that complex, you might be able to track down the problem :blush: 
Here's the suspicious line I have in mind: https://github.com/pierpo/react-archer/blob/master/src/ArcherElement.js#L29

Thanks!

**Comment by InstantProgramming** [comment]
![issueReduxChanges](https://user-images.githubusercontent.com/188211/55688734-56e25100-597c-11e9-9c4f-4742627a7696.PNG)
![issueReduxStates](https://user-images.githubusercontent.com/188211/55688735-59dd4180-597c-11e9-8365-67de5313f581.PNG)

Here are screens of the change and the relations Props given to the component.
Ok thanks for the advice i will check that this week

**Comment by pierpo** [comment]
Strange, it should be fine...

I'll try to reproduce when I'll have some time.

**Comment by InstantProgramming** [comment]
![issueGIF2](https://user-images.githubusercontent.com/188211/56322209-b6a0df00-6168-11e9-8e65-636d5d7bdd0e.gif)
Very Strange ... When i change it manually from react Debugger it looks like updating correctly but when the same thing is done from the onClick with props and redux it does nothing

**Comment by InstantProgramming** [comment]
My Bad, I was making a bad clone of the Relations and that caused the prevProps to be the same as this.props , insted of doing :
let newColumnsRelations = Array.from(columnsRelations);
I did now : 
let newColumnsRelations = JSON.parse(JSON.stringify(columnsRelations));
and all works good now ! 
I close the issue 💯

**Comment by pierpo** [comment]
Fantastic, glad that you could find the issue 😊
