### ISSUE TITLE
End of the arrow pointing in the wrong direction

### ISSUE THREAD

**Issue by emidiotorre** [pierpo/react-archer#89]
Hi, first of all, thanks for this beautiful and simple library!
I'm working on a tool to visualize relationships in text, I would like to display arrows alongside the text, the text can be disposed vertically or horizontally.

in the vertical scenario what I'm getting now is this
![react-archer-bug](https://user-images.githubusercontent.com/10254639/79687983-3c0f1180-824b-11ea-83d9-0919777747b2.png)

and this is a portion of the relationship object:
`           targetAnchor: "left",
            sourceAnchor: "left",
            style: {
              strokeColor: "#c0c0c0",
              strokeWidth: 2,
              strokeDasharray: 2,
              arrowLength: 0,
              arrowThickness: 0,
              noCurves: true,
            },`

I don't understand why this is happening.

Just gave a quick glimpse at the source code, and would be happy to purpose a pull request if you can give me some advice!

Thanks!

P.S. It would be also nice to have the possibility of not drawing the pointer, and instead draw just a line

**Comment by pierpo** [comment]
Hello!
Thank you for the kind words :blush: 

> the possibility of not drawing the pointer

If I remember correctly, putting "arrowLength" to 0 makes it possible.
(I just realized this props was poorly named, it should be "arrowHeadLength").

About the bug itself, I'll have a quick look!

**Comment by pierpo** [comment]
Oops, actually setting `arrowLength` to 0 does not hide the arrow.

**Comment by pierpo** [comment]
I just opened a PR to allow the `arrowLength: 0` in order to hide the arrow heads.

However, about your bigger issue... The task is not as simple, there have to be core changes in order to make this work.

When I designed the library in the first place I only had in mind "left to right" scenarios, I had not thought about "left to left" like yours.

If I'm correct, the problem lies here https://github.com/pierpo/react-archer/blob/2b1d963a88468cf39843621e68a9f40aee3f52a7/src/SvgArrow.js#L21

More changes have to be made in order to make this work. I think we need to determine where the arrow comes from before computing the path. Maybe there's more to it, I don't have clear ideas about it right now :thinking: 

You can have a look at how it works right now (might take half an hour maybe?) and you can think of a solution if it's blocking for you. I'd gladly discuss it :blush:

**Comment by pierpo** [comment]
(by the way, this issue is the same problem: https://github.com/pierpo/react-archer/issues/69)
