### ISSUE TITLE
Typescript migration - refactor and bug fixes

### ISSUE THREAD

**Issue by gurkerl83** [pierpo/react-archer#99]
In the last few days, I've spent a little time trying to make my application compatible with the latest changes in react archer. I've noticed a few things that could be made better and easier. I took the components as they are in the latest version of react-archer and integrated them directly into my project. For more information, see the following ticket or pull request in my application. 

Issue description
https://github.com/project-millipede/millipede-docs/issues/202

Commit
https://github.com/project-millipede/millipede-docs/commit/ac8fd2b169bd445bbb0138477d5346e4a42226b7

Link to a demo
https://millipede.me/perspective/strategy

Among other things, the modifications solve recent compatibility problems and breaking changes of react-archer. If the authors of react-archer are interested, I can also provide the changes as pull requests in react archer. Of course, this requires some further adjustments in the build process of the library, where the sources got entirely migrated to typescript.

Please tell me what you think, feasible or not.

Thx!

**Comment by pierpo** [comment]
Hello,

Thank you so much for this! Looks like I messed some things up with 2.0. I'll have a deep read of your issue and I'll try to fix it ASAP!

**Comment by pierpo** [comment]
And for sure I am interested in a PR or other comments on things you might have improved :blush:

**Comment by pierpo** [comment]
Okay, I carefully read everything! Your work will be really precious, I love how you detailed everything, thank you for that.

So, with my last breaking commit, I missed the React Components as children case. Which leaves a huge issue :grimacing: (quite angry at myself for that).

The problem we have with components is that they don't have a ref, since they potentially don't represent a single element in the DOM.
You pointed out the mis-usage of `React.only` and you're perfectly right :grimacing: 

Still, I'm having a hard time understanding what your changes have on the API?
Is that what you achieve?

| `<ArcherElement>...</ArcherElement>` | Works ? |
| - | - |
| `<div />` | :white_check_mark: 
| `<div /> <div />` | :white_check_mark: 
| `<OneChildComponent />` | :white_check_mark: 
| `<OneChildComponent /> <OneChildComponent />` | :x: 
| `<TwoChildrenComponent />` | :x:

Something else I don't understand: you say you don't need to create a fake element. But whose reference do you get? How do you know what element in your child component acts as the drawing reference? Do you need the user to pass a ref somehow?

Thank you!

**Comment by gurkerl83** [comment]
Hi thanks for the interest in the changes I made. This is just the first version for your questions. I answer the more pressing questions in a follow up writing.

See example below. Important lines are highlighted with (***). This is a standard component, which accepts an existing reference with Reacts forward reference API. It receives the ref but it is not assigned (even with clone), so the developer has to assign by her / himself.

```<ArcherElement>...</ArcherElement>``` | Works!
------------ | -------------
```<div />``` | Works
```<div /> <div />``` | Does not work because without a wrapper (fake element) clone does not know which of the two divs get the ref copied to. Maybe there is something in clone that it assigns to the first element but this is unknown to me.
```<OneChildComponent />``` | Works. A component needs to accepts the ref. The developer of the component has to ensure that.
```<OneChildComponent /> <OneChildComponent />``` | Does not work same reason as ```<div /> <div />```
```<TwoChildComponentWorksNesting />``` | Works. Arbitrary nesting in the component works just fine.
```<TwoChildComponentWorksPartially />``` | Works Partially. See comments of the component.


```
export const OneChildComponent: ForwardRefRenderFunction<
  HTMLDivElement,
  OneChildComponentProps
> = ({ children }, ref) => { ***
  return (
    <div
      ref={ref} ***
    >
      {children}
    </div>
  );
};

export default forwardRef(OneChildComponent); ***
```

```
export const TwoChildComponentWorksNesting: ForwardRefRenderFunction<
  HTMLDivElement,
  TwoChildComponentWorks
> = ({ children }, ref) => { ***
  return (
    <div
      ref={ref} ***
    >
        <div>
            {children}
        </div>
    </div>
  );
};

export default forwardRef(TwoChildComponentWorks); ***
```

```
export const TwoChildComponentWorksPartially: ForwardRefRenderFunction<
  HTMLDivElement,
  TwoChildComponentWorks
> = ({ children }, ref) => { ***
    return (
    <> ***Corresponds to React fragment component
        <div
            ref={ref} ***Tracked div
        >
            <div>
                {children}
            </div>
        </div>
        <div/> ***Measurement is not taken into account because it is not tracked
    </>
  );
};

export default forwardRef(TwoChildComponentWorks); ***
```

**Comment by gurkerl83** [comment]
> The problem we have with components is that they don't have a ref, since they potentially don't represent a single element in the DOM.

With this question, you mean basically example TwoChildComponentWorksPartially? 

Components can only render two divs on the 0-level when Reacts fragment component gets used. When you do it in typescript, you at least get the following message JSX expressions must have one parent element. Nevertheless, using a fragment, the developer has to decide which div to track.

**Comment by pierpo** [comment]
Thank you for your answer! Everything seems very clear but this point: if I understand correctly, the dev-user would need to wrap his components with `forwardRef` so that he can specify what child node is the drawing reference.

Is that correct?

**Comment by gurkerl83** [comment]
> Thank you for your answer! Everything seems very clear but this point: if I understand correctly, the dev-user would need to wrap his components with `forwardRef` so that he can specify what child node is the drawing reference.

The wrapping into forwardRef is only necessary so that the parent (here archer-element can pass a reference into the functional or class component). When the reference (placeholder because it is empty and filled on assignment to the target node) received, the developer decides which node the reference gets assigned within the component.

***Note***
The examples provided are functional components, Reacts forwardRef function is most important. According to the react documentation using class-based components, you have to use forwardRef function too, even when the setup is a bit more complicated. The property ref is not available at component props at all!

Hope now it more understandable.

**Comment by pierpo** [comment]
Haha unfortunately, still not 100%.
Can you provide me short examples of the targeted API we'd achieve with your changes?

With the suggested changes, would this work? Would this need a forwardRef?

Thank you, sorry for having a hard time understanding :wink: 

```jsx
const MyComponent = () => (
  <div>hello</div>
);

// ...
<ArcherElement><MyComponent /></ArcherElement>
```

**Comment by gurkerl83** [comment]
Sure no problem! Of course this is a component and requires a wrapping.

// TS version

```typescript
const MyComponent: ForwardRefRenderFunction<HTMLDivElement, null> = (
  // eslint-disable-next-line no-empty-pattern
  {},
  ref
) => <div ref={ref}>hello</div>;

export default forwardRef(MyComponent);
```
// JS version

```javascript
const MyComponent = (
  // eslint-disable-next-line no-empty-pattern
  {}, // the first argeument are the normal props passed
  ref // the second argument is ref which forwardref passes when it sees a ref in the archer-element
) => <div ref={ref}>hello</div>;

export default forwardRef(MyComponent);
```

**Comment by pierpo** [comment]
Alright, now it is almost crystal clear :blush:

I do have one last doubt: I'm not sure I understand what your changes are on the refs because if I use `forwardRef` with the current implementation, then the problem is solved.

Are you sure you're not confusing the old way of creating refs (through a callback as I did) with the new way (through hooks or createRef, like you did)?

___

As written above, there is actually "no bug" if we only consider that an API change. You simply need to wrap your component with `forwardRef` or in a div.

But I don't really like this approach :thinking: 
It makes the library harder to use.

Here are the options I see. I'd love to add more if you can think of some. @jfo84 I would love your help here :blush: 

1) Revert back to everything it was 1.6.0. Add a `div` internally and use the ref of this div. Add an additional flag to enable the new behaviour, something like `accurateDrawing` (???) and mention explicitely in the doc that to use this flag with a component you need your component to have a `forwardRef`
2) Keep the new behaviour (no fake div), and maybe have a way to catch the problem at runtime. Document explicitely that you can wrap your element with a `div` if it works with your layout or use `forwardRef`
3) ...?

Thank you!!

**Comment by pierpo** [comment]
About this:

> Could you please remove the Bug label, because here is no bug at least not in the reimplementation of mine for the archer element.

> For the current version it is a bug. If I remember correctly it is the use of the ref function in combination with forward refs.

You answered your question yourself: right now there is a problem/bug in the current implementation :wink: 
Let's keep the "bug" label to know what we're referring to and so that people can see it. If you want you can open another issue where we'll talk about your improvements of the lib :blush:

**Comment by gurkerl83** [comment]
Not sure which way to go. One thing is for sure, having different config options, most certainly confuses people using the library in the first place. Using forwardRef for components is the only way React supports; there are no options about that.

A small thing to note about the comment from above: You can only use createRef in class-based components; it is no hook. UseRef (hook) is the equivalent for functional components; most importantly, you can only use hooks in functional components, but not in class-based components!

Maybe you can decide which way to go. Unfortunately I have no cycles left, maybe next week, sry!

**Comment by pierpo** [comment]
I've migrated the code base to typescript + hooks. I'll keep working on further refactorings :blush: (most notably: split stuff)
